from pathlib import Path
p=Path('assets/presence.css')
s=p.read_text(encoding='utf-8').replace('.frame-statement p span{color:#93774f}', '.frame-statement p span{color:#876940}').replace('.footer-bottom{color:#787878}', '.footer-bottom{color:#707070}').replace('.coverage-tabs button[aria-selected=true]{background:#2d2d2d;color:white}', '.coverage-tabs button[aria-selected=true]{background:#2d2d2d;color:white}.coverage-tabs button[aria-selected=true]>span{color:#ddd0bc}')
p.write_text(s,encoding='utf-8')
p=Path('scripts/audiences.py')
s=p.read_text(encoding='utf-8')
start=s.index('def hero():')
end=s.index('def perspectives():')
s=s[:start]+s[end:]
s=s.replace('Audience journeys and the cinematic homepage introduction.', 'Audience journeys and policy-to-capital research interactions.')
p.write_text(s,encoding='utf-8')
p=Path('scripts/build.py')
s=p.read_text(encoding='utf-8').replace('cinematic_hero','research_hero')
p.write_text(s,encoding='utf-8')
p=Path('README.md')
s=p.read_text(encoding='utf-8').replace('`scripts/audiences.py`: cinematic homepage opening, government affairs and distressed-debt journeys, and illustrative research interactions.', '`scripts/audiences.py`: government affairs and distressed-debt journeys, and illustrative research interactions.\n- `scripts/experience.py`: centered homepage hero, research-question preview, six briefing formats, and FAQs.').replace('`assets/presence.css`: dark hero treatment, audience pages, short motion, and interactive brief presentation.', '`assets/presence.css`: Zite-inspired white, charcoal, and gold theme; serif typography; responsive audience pages and interactive research previews.')
p.write_text(s,encoding='utf-8')
p=Path('docs/AUDIENCE-CONTENT-PLAN.md')
s=p.read_text(encoding='utf-8').replace('Midnight blue and warm coral in the opening, with the paper/violet editorial system retained below.', 'Zite-inspired white space, charcoal serif headlines, warm gold accents, pill-shaped calls to action, and subtle lavender section backgrounds. The industrial image sits below the centered headline with an interactive, explicitly illustrative research preview.')
p.write_text(s,encoding='utf-8')
