from pathlib import Path
p=Path('scripts/build.py'); s=p.read_text(encoding='utf-8')
s=s.replace('from experience import hero as research_hero, formats, faq','from experience import hero as research_hero, formats, faq\nfrom depth import PAGES, write_downloads\nfrom samples import SAMPLES, sample_library, sample_page, write_sample_downloads\nfrom site_navigation import navigation, home_directory')
start=s.index("    nav = [",s.index('def layout(')); end=s.index("    return f'''",start)
s=s[:start]+"    links = navigation(prefix)\n"+s[end:]
s=s.replace('<link rel="stylesheet" href="{prefix}assets/presence.css">','<link rel="stylesheet" href="{prefix}assets/presence.css"><link rel="stylesheet" href="{prefix}assets/depth.css">')
s=s.replace('research_hero()+perspectives()+programme_teaser()+', 'research_hero()+perspectives()+programme_teaser()+home_directory()+')
s=s.replace('<a href="{prefix}government-affairs.html">Government affairs</a><a href="{prefix}distressed-debt.html">Distressed debt</a>', '<a href="{prefix}capabilities.html">Research capabilities</a><a href="{prefix}government-affairs.html">Government affairs</a><a href="{prefix}distressed-debt.html">Distressed debt</a>')
s=s.replace('<a href="{prefix}about.html">About EchoFrame</a>', '<a href="{prefix}about.html">About EchoFrame</a><a href="{prefix}trust.html">Trust &amp; privacy</a><a href="{prefix}sample-briefs.html">Sample briefs &amp; templates</a><a href="{prefix}sources.html">Primary-source directory</a>')
s=s.replace('<a href="{prefix}briefing.html">Book a briefing</a><a href="mailto:', '<a href="{prefix}briefing.html">Book a briefing</a><a href="{prefix}engagement.html">Working with EchoFrame</a><a href="mailto:')
s=s.replace("    validate(); globe()", "    validate(); globe()\n    downloads = write_downloads() + write_sample_downloads()\n    for path, title, render, key in PAGES:\n        write(path, title, render(), key)\n    write('sample-briefs.html','Sample briefs & templates',sample_library(),'samples')\n    for sample in SAMPLES:\n        write(sample['slug']+'.html',sample['title'],sample_page(sample),'sample')")
s=s.replace("'assets/presence.css', 'assets/site.js'", "'assets/presence.css', 'assets/depth.css', 'assets/site.js'")
s=s.replace("files += ['images/'", "files += downloads\n    files += ['images/'")
# Expand the enquiry form while preserving existing fields and audience routing.
s=s.replace('<label>Your name<input', '<div class="enquiry-grid"><label>Your name<input')
s=s.replace('<label>Region of interest<select', '<label>Your role<input name="role" autocomplete="organization-title" maxlength="160" placeholder="Role or team"></label><label>Phone number<input name="phone" type="tel" autocomplete="tel" maxlength="60" placeholder="Optional, with country code"></label><label>Headquarters / location<input name="headquarters" maxlength="160" placeholder="City or country"></label><label>Region of interest<select')
s=s.replace('<label>What would you like to understand?<textarea', '<label>Research format<select name="format"><option>To discuss</option><option>Scoping conversation</option><option>Focused research brief</option><option>Recurring research review</option><option>Stakeholder mapping</option><option>Thesis-assumption review</option></select></label><label>How did you find EchoFrame?<select name="referral"><option>Prefer not to say</option><option>Colleague or professional referral</option><option>LinkedIn</option><option>Search</option><option>Event or publication</option></select></label></div><label>What would you like to understand?<textarea')
s=s.replace('Prepares a message for your email app. Nothing is sent until you send it. You can also copy the request below.', 'Prepares a message for your email app. Nothing is sent until you send it. You can also copy the request below. <a href="privacy.html">How your information is handled</a>.')
s=s.replace('<section class="briefing-layout container">','<section class="briefing-layout container expanded-enquiry">')
s=s.replace("    return result+cta()\n\n\ndef methodology", "    return result+cta()\n\n\ndef methodology")
p.write_text(s,encoding='utf-8')
p=Path('scripts/audiences.py'); s=p.read_text(encoding='utf-8')
s=s.replace('def audience_page(key):','from depth import audience_depth\n\n\ndef audience_page(key):')
s=s.replace('<section class="audience-close">', '{audience_depth(key)}<section class="audience-close">')
p.write_text(s,encoding='utf-8')
