"""Case study. The Venezuela call, with the client described only by type."""


def page(intro):
    return intro(
        'Case study / Venezuela',
        'A call made before the outcome',
        'A distressed credit fund asked for four pressure points to be watched. This is what the record showed, what '
        'we concluded from it, and the part of the reasoning that was wrong.'
    ) + '''<section class="section container" id="the-question"><div class="section-heading"><div><div class="eyebrow">The question</div><h2>Four pressure points, watched daily</h2></div></div><div class="prose-page"><p>In October a distressed credit fund holding Venezuelan debt came to us with a bespoke question. They wanted the pressure points watched. Unrest on the streets, the risk of the armed forces fracturing or moving against the government, the cohesion of the elite around Maduro, and the pressure the United States was applying to Caracas.</p><p>We ran it as a time series. Every day of reporting became dated events with named actors, and those events moved four readings we track separately rather than collapsing into one number.</p></div></section>
<section class="section container" id="the-readings"><div class="section-heading"><div><div class="eyebrow">The readings</div><h2>Four lines, not one number</h2></div></div><div id="venezuela-series"></div><p class="visual-caption">Every point is computed forward only, using events first seen on or before that date.</p></section>
<section class="section container" id="the-call"><div class="section-heading"><div><div class="eyebrow">The call</div><h2>The gap between the lines</h2></div></div><div class="prose-page"><p>Through the second half of November, pressure from outside and fracture inside the elite both spiked, and ran that way for almost two weeks. On 2 December we made the call. A minority probability on a major political rupture within thirty days.</p><p>The reading behind it was the gap between the lines. Pressure from outside was climbing and jumped again in the last week of November. Elite cohesion had been falling all autumn and turned up off its low at the start of December. The military reading went the other way and sat at its lowest point on the day we made the call.</p><p>So the pressure from outside was building and the circle around Maduro was starting to come apart, while the armed forces were still holding. Our judgement was that the military line could not hold against the other two, and that when it went it would go quickly. That is why the call was a rupture rather than a slow decline, and why we put it at a minority probability rather than higher.</p></div></section>
<section class="section container" id="what-happened"><div class="section-heading"><div><div class="eyebrow">What happened, and what we got wrong</div><h2>The outcome held, the mechanism did not</h2></div></div><div class="prose-page"><p>The military reading rose sharply over the last two weeks of December. Maduro was taken on 3 January, thirty two days after the call.</p><p>We weighted a negotiated exit above a strike. The strike came first. The call was about the outcome rather than the mechanism, which is why it held anyway, and it is the reason we write the outcome and the mechanism as separate questions now.</p><p>The client positioned for succession inside the existing structure rather than for collapse or for the opposition taking power, which was the consensus in the press at the time. The contract and counterparty assumptions that followed from that reading were the ones that held.</p></div></section>'''
