"""English and Spanish framing for the public GIS demonstration."""
import re


def map_page(layout, brand, lang='en'):
    es = lang == 'es'
    prefix = '../' if es else ''
    def t(en, spanish):
        return spanish if es else en

    title = t('Event records in eastern Venezuela', 'Registros de eventos en el oriente de Venezuela')
    introduction = t(
        'This map covers Monagas and Anzoátegui over two years. It shows event records built from licensed and permitted sources, with corroboration determined by an explicit rule. It contains no article text. The question probabilities are provisional hindcasts, not a track record.',
        'Este mapa abarca Monagas y Anzoátegui durante dos años. Muestra registros de eventos elaborados a partir de fuentes con licencia o uso permitido, con una regla explícita de corroboración. No contiene textos de artículos. Las probabilidades son estimaciones retrospectivas provisionales, no un historial de resultados predictivos.')
    body = f'''<div class="container gis-page" data-gis-demo data-language="{lang}" data-root="{prefix}assets/gis-demo/">
<section class="gis-intro"><div class="eyebrow">PRISMA / {t('Public demonstration', 'Demostración pública')}</div>
<h1>{title}</h1><p>{introduction}</p><a class="text-link" href="#map-notes">{t('Read the definitions and limits', 'Leer las definiciones y los límites')}</a></section>
<section class="gis-workspace" aria-label="{t('Explore the event record', 'Explorar los registros de eventos')}">
<div class="gis-controls"><div><label for="gis-month">{t('Month of first observation', 'Mes de primera observación')}</label><output id="gis-month-label" for="gis-month"></output></div>
<button id="gis-play" type="button" disabled aria-pressed="false">{t('Play', 'Reproducir')}</button><input id="gis-month" type="range" min="0" max="23" value="23" step="1" disabled>
<div class="gis-range"><span>{t('Oct 2024', 'Oct 2024')}</span><span>{t('Sep 2026 · partial month', 'Sep 2026 · mes parcial')}</span></div></div>
<p id="gis-status" class="gis-status" role="status">{t('Loading the exported records', 'Cargando los registros exportados')}</p>
<button id="gis-retry" type="button" hidden>{t('Retry loading', 'Reintentar la carga')}</button>
<div class="gis-grid"><div class="gis-map-column"><div id="gis-map" role="region" aria-label="{t('Interactive map of Monagas and Anzoátegui', 'Mapa interactivo de Monagas y Anzoátegui')}"></div>
<p id="gis-basemap" class="gis-credit">{t('Checking the basemap', 'Comprobando el mapa base')}</p>
<div class="gis-legend"><div><strong>{t('Municipalities', 'Municipios')}</strong><div class="gis-scale"><i></i><span>0</span><span>1</span><span>2</span><span>4+</span></div><small>{t('Corroborated events first seen in the selected month', 'Eventos corroborados observados por primera vez en el mes seleccionado')}</small></div>
<div><strong>{t('Event status', 'Estado de corroboración')}</strong><span><i class="gis-dot confirmed"></i>{t('Corroborated', 'Corroborado')}</span><span><i class="gis-dot single"></i>{t('Single source', 'Fuente única')}</span><span><i class="gis-dot disputed"></i>{t('Contradicted', 'Contradicho')}</span></div>
<div><strong>{t('Severity and precision', 'Gravedad y precisión')}</strong><span class="gis-severity"><i></i><i></i><i></i>{t('Low, medium, high', 'Baja, media, alta')}</span><span><i class="gis-dot unknown"></i>{t('Unknown severity is hollow', 'Gravedad desconocida sin relleno')}</span><span><i class="gis-area"></i>{t('State record shown as an area', 'Registro estatal mostrado como área')}</span></div>
<div><strong>{t('Assets', 'Activos')}</strong><span><i class="gis-dot asset"></i>{t('Approximate asset location', 'Ubicación aproximada del activo')}</span><span><i class="gis-radius"></i>{t('25 km reference radius', 'Radio de referencia de 25 km')}</span><small>{t('The radius does not determine event membership.', 'El radio no determina la asignación de eventos.')}</small></div></div></div>
<aside class="gis-panel" aria-label="{t('Record details', 'Detalles del registro')}"><div class="eyebrow">{t('Inspect a record', 'Examinar un registro')}</div>
<label for="gis-event">{t('Events in this month', 'Eventos de este mes')}</label><select id="gis-event" disabled></select>
<label for="gis-asset">{t('Assets and question scopes', 'Activos y ámbitos de las preguntas')}</label><select id="gis-asset" disabled></select>
<div id="gis-detail" tabindex="-1"><h2>{t('Select an event or asset', 'Seleccione un evento o activo')}</h2><p>{t('Use the map or the lists above. State records and assets without resolved coordinates remain available in the lists.', 'Utilice el mapa o las listas. Los registros estatales y los activos sin coordenadas resueltas siguen disponibles en las listas.')}</p></div></aside></div>
<section class="gis-chart-section" aria-labelledby="gis-chart-heading"><div><div class="eyebrow">{t('The exported record', 'Los registros exportados')}</div><h2 id="gis-chart-heading">{t('Corroborated events by month', 'Eventos corroborados por mes')}</h2><p>{t('Includes state-level records. A zero is an absence in this export, not evidence of normal conditions.', 'Incluye registros a nivel estatal. Un cero indica ausencia en esta exportación, no demuestra condiciones normales.')}</p></div><div id="gis-chart"></div><details class="gis-table"><summary>{t('Read the monthly counts', 'Consultar los recuentos mensuales')}</summary><div id="gis-counts"></div></details></section>
</section>
<section id="map-notes" class="gis-notes"><div><div class="eyebrow">{t('Definitions and limits', 'Definiciones y límites')}</div><h2>{t('How to read this demonstration', 'Cómo interpretar esta demostración')}</h2></div><div>
<h3>{t('Corroboration', 'Corroboración')}</h3><p>{t('An event is corroborated by two media outlets with different known owners and home cities, or by a media source and a qualifying non-media source. A contradicted record contains an assertion and a denial from a normally trusted source. Source count counts contributing items, not independent outlets. Source blocks describe categories without identifying people.', 'Un evento se corrobora mediante dos medios con propietarios y ciudades de origen distintos y conocidos, o mediante un medio y una fuente no periodística que cumpla los criterios. Un registro contradicho contiene una afirmación y una negación de una fuente habitualmente fiable. El recuento de fuentes cuenta elementos aportados, no medios independientes. Los bloques describen categorías sin identificar a personas.')}</p>
<h3>{t('Location and severity', 'Ubicación y gravedad')}</h3><p>{t('Municipality points are display centroids, not incident locations. State records cover the state polygon. Asset coordinates are approximate and unresolved sites have no pin. Two stored points fall outside their recorded state boundary and remain flagged. Severity describes the extent of an event, not confidence in it. All events in this export have unknown severity.', 'Los puntos municipales son centroides de visualización, no lugares exactos de los hechos. Los registros estatales cubren el polígono del estado. Las coordenadas de activos son aproximadas y los sitios sin resolver no tienen marcador. Dos puntos están fuera del límite de su estado registrado y conservan esa advertencia. La gravedad describe la magnitud del evento, no la confianza en él. Todos los eventos de esta exportación tienen gravedad desconocida.')}</p>
<h3>{t('Dates and probabilities', 'Fechas y probabilidades')}</h3><p>{t('The source window starts on 11 September 2024. The slider shows the latest 24 calendar months, from October 2024 to September 2026. The snapshot is dated 12 September 2026 and the last collected event is dated 10 September. Events are counted in their first-seen month. Freshness and corroboration are stored snapshot labels, not reconstructed historical verdicts. Weekly asset counts use exact asset assignments and show completed weeks only. Questions show the last stored hindcast available by the selected date, while the question remains open. These retrospective, indicative probabilities are neither live forecasts nor an evaluated track record.', 'La ventana de origen comienza el 11 de septiembre de 2024. El control muestra los últimos 24 meses naturales, de octubre de 2024 a septiembre de 2026. La exportación está fechada el 12 de septiembre de 2026 y el último evento recopilado, el 10 de septiembre. Los eventos se cuentan en su mes de primera observación. La vigencia y la corroboración son etiquetas almacenadas, no dictámenes históricos reconstruidos. Las series semanales usan asignaciones exactas a activos y muestran solo semanas completas. Las preguntas muestran la última estimación retrospectiva almacenada hasta la fecha seleccionada, mientras la pregunta sigue abierta. Estas probabilidades indicativas no son pronósticos en tiempo real ni un historial evaluado.')}</p>
<h3>{t('Collection limits', 'Límites de recopilación')}</h3><p>{t('The eastern reporting network lacks an independent second local source. Facility coverage is limited by place resolution. VIIRS observations are available only from 7 September 2026. Missing evidence cannot establish normal operations.', 'La red de información del oriente carece de una segunda fuente local independiente. La cobertura de instalaciones está limitada por la resolución geográfica. Las observaciones VIIRS están disponibles solo desde el 7 de septiembre de 2026. La falta de evidencia no demuestra operaciones normales.')}</p>
<h3>{t('Boundaries and permitted use', 'Límites administrativos y uso permitido')}</h3><p>{t('The administrative boundaries are drawn from OpenStreetMap. Selection and coordinate rounding are applied for this page. The boundary database is available under the Open Database Licence. The event records contain no article text. Each contributing source passed the export’s permitted-use and source-protection checks.', 'Los límites administrativos proceden de OpenStreetMap. Esta página aplica selección y redondeo de coordenadas. La base de límites se ofrece bajo la Open Database Licence. Los registros no contienen textos de artículos. Cada fuente aportada superó los controles de uso permitido y protección de fuentes de la exportación.')}</p>
<p><a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a> · <a href="{prefix}assets/gis-demo/LICENSE.txt">ODbL 1.0</a> · <a href="{prefix}assets/gis-demo/boundaries.json">{t('Boundary data', 'Datos de límites')}</a></p>
<a class="button" href="{prefix}briefing.html?format=Asset%20Watch">{t('Discuss your asset coverage', 'Consultar la cobertura de sus activos')}</a></div></section></div>'''
    result = layout(title, body, 'map', prefix, introduction, lang)
    extras = f'''<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/maplibre-gl/5.24.0/maplibre-gl.css"><link rel="stylesheet" href="{prefix}assets/map.css"><script defer src="https://cdnjs.cloudflare.com/ajax/libs/maplibre-gl/5.24.0/maplibre-gl.js"></script><script defer src="{prefix}assets/map.js"></script><link rel="alternate" hreflang="en" href="{prefix}map.html"><link rel="alternate" hreflang="es" href="{prefix}es/map.html">'''
    result = result.replace('</head>', extras + '</head>')
    result = re.sub(r'<div class="topline">.*?</div></div>', '', result)
    nav = f'''<header class="site-header"><div class="container nav-shell">{brand(prefix)}<button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">{t('Menu', 'Menú')}</button><nav id="main-nav" aria-label="{t('Main navigation', 'Navegación principal')}"><a href="{prefix}venezuela.html">Venezuela{t('', ' (en inglés)')}</a><a href="{prefix}methodology.html">{t('Methodology', 'Metodología (en inglés)')}</a><a href="{prefix + 'map.html' if es else 'es/map.html'}" lang="{t('es', 'en')}">{t('Español', 'English')}</a><a class="nav-contact" href="{prefix}briefing.html">{t('Request a demo', 'Solicitar una demostración')}</a></nav></div></header>'''
    result = re.sub(r'<header class="site-header">.*?</header>', lambda _: nav, result, flags=re.S)
    footer = f'''<footer class="site-footer"><div class="container"><div class="footer-bottom"><span>© 2026 EchoFrame Intelligence AB</span><a href="{prefix}privacy.html">{t('Privacy', 'Privacidad (en inglés)')}</a><a href="#main">{t('Back to top', 'Volver al inicio')}</a></div></div></footer>'''
    result = re.sub(r'<footer class="site-footer">.*?</footer>', lambda _: footer, result, flags=re.S)
    if es:
        result = result.replace('Skip to content', 'Saltar al contenido').replace('aria-label="EchoFrame home"', 'aria-label="Inicio de EchoFrame"')
    return result
