"""Public programme copy adapted from the supplied September 2026 working plan.

This module describes the product direction; it does not implement a signal engine.
"""
from intelligence import brief_structure

# Retained for future editing; intentionally excluded from the public page.
UNPUBLISHED_VENEZUELA_SECTIONS = """<section class="section container"><div class="section-heading"><div><div class="eyebrow">03 / Proposed collection priorities</div><h2>Three zones.<br>Specific local questions.</h2></div><p>Initial collection priorities are Zulia, Monagas, Bolívar, and Anzoátegui. These are programme priorities, not a claim of contracted field coverage.</p></div><div class="zone-grid"><article><div class="eyebrow">Oriente</div><h3>Anzoátegui & Monagas</h3><p>Proposed focus: the José complex, fields and upgraders, and the connections between operations, labour, contractors, and local authorities.</p><ul><li>Loading, shut-ins, restarts, and inputs</li><li>Arrears, stoppages, and contractor payment</li><li>Access, community concerns, and local control</li></ul></article><article><div class="eyebrow">Occidente</div><h3>Zulia; Falcón as scope expands</h3><p>Proposed focus: the Lake Maracaibo area and, as demand supports it, the Paraguaná refining area.</p><ul><li>Field and refinery operating conditions</li><li>Spills and fishing-community concerns</li><li>Contractor access and infrastructure</li></ul></article><article><div class="eyebrow">Guayana</div><h3>Bolívar; Delta Amacuro as scope expands</h3><p>Proposed focus: power, industrial activity, mining-related questions, and potential extension to Delta assets.</p><ul><li>Grid reliability and industrial constraints</li><li>Local authority and community positions</li><li>Navigation and asset access</li></ul></article></div><p class="collection-note">Collection scope depends on the questions commissioned, source access, and the ability to report safely. A more detailed map should only appear when the evidence supports that precision.</p></section>
<section class="viability-section container"><div><div class="eyebrow">04 / Two views of the same asset</div><h2>Operational evidence.<br><em>Documented viability.</em></h2><p>A report about activity and a judgment about an asset’s contractual position answer different questions. The intended brief presents them alongside one another.</p></div><div><h3>Six asset-specific checks</h3><ul class="viability-list"><li>Contract standing</li><li>Licence and sanctions standing</li><li>Arbitration exposure</li><li>Counterparty solvency</li><li>Operational access</li><li>Security of tenure</li></ul><p class="fine-print">These document checks sit beneath the wider six decision tests: rule of law, enforceable contracts, predictable rules, infrastructure, credible institutions, and policy continuity. A check without supporting evidence remains unassessed.</p></div></section>
<section class="section container"><div class="section-heading"><div><div class="eyebrow">05 / Product direction</div><h2>A brief you can trace.<br>A forecast you can review.</h2></div></div><div class="standards-grid"><div><h3>The question register</h3><p>Named subjects, fixed wording, deadlines, resolution rules, and the assumptions behind each initial assessment.</p></div><div><h3>The zone brief</h3><p>A dated event record, the accounts that support or dispute it, location precision, and an analyst’s next verification step.</p></div><div><h3>The resolution record</h3><p>Forecast revisions preserved before outcomes are known. Results assessed against a defined evaluation policy and benchmark.</p></div></div><p class="collection-note">The sections above explain the intended brief structure. Forecast performance needs a complete dated record, defined resolution rules, and a benchmark; the selected historical case above is not that evaluation.</p><a class="text-link" href="briefing.html?region=Venezuela">Discuss a Venezuela research question </a></section>"""


def _unused_programme_teaser():
    return '''<section class="programme-teaser container"><div><div class="eyebrow"><span class="status-dot orange"></span> Lead development programme / Venezuela</div><h2>National context.<br><em>Asset-level questions.</em></h2></div><div><p>What is happening around a terminal, a field, or a contract? We are developing a clearer view of local events, competing claims, and the evidence needed to resolve a client’s question.</p><a class="text-link" href="venezuela.html">Inside the Venezuela programme </a></div></section>'''


def question_preview():
    return ''


def venezuela_page(intro, cta):
    return intro('EchoFrame Venezuela / Country direction and commercial exposure', 'Understand the paths ahead<br><em>Test what they mean for you</em>', 'Venezuela reporting, turned into a structured assessment of risk, dated questions and the conditions an opportunity must meet. Start with the country picture, then work down to the decision on your desk.')+brief_structure() + '''
<section class="programme-note container"><span class="eyebrow">Where the programme stands</span><p>The product framework brings risk dimensions, dated questions and commercial criteria together. Collection scope, delivery cadence, and access are agreed for each engagement.</p></section>

''' + cta()


def evidence_methodology(intro, cta):
    stages = [
        ('Collection', 'Keep the source, event and publication times, collection time, and permitted use attached to each item. Source material without reviewed usage rights must not enter a client output.', 'Foundation reported in the working plan; rights controls need completion.'),
        ('Indexing', 'Find material relevant to a question. Similarity and topic attention help locate evidence; they do not establish an event’s truth or the probability of an outcome.', 'Existing research foundation. Attention measures are not risk probabilities.'),
        ('Places, actors & event types', 'Extract where an item refers to, who is involved, and what kind of event it describes. Preserve uncertain or unmatched references for review.', 'Extraction components need to be connected and their outputs retained.'),
        ('Location & precision', 'Relate events to assets and administrative areas. A state-level report should be shown at state level, not as an apparently precise facility pin.', 'Spatial event analysis is planned.'),
        ('Events & corroboration', 'Group reports about the same event, inspect whether their sources are independent, and preserve both supporting and contradictory accounts. Keep freshness visible as a separate property.', 'Event grouping and corroboration are planned.'),
        ('Asset viability', 'Keep analyst judgments about contractual and operating viability alongside event evidence. Cite the document behind each assessed criterion and flag missing evidence.', 'An analyst-fed component is reported to exist; client presentation and event-triggered review need integration.'),
        ('Question-level inference', 'Define a question, its initial judgment, and the evidence that could change it. Record the rationale for updates. Evidence weights require review and evaluation before any claim of calibrated probability.', 'A connected question-forecasting workflow is in development.'),
        ('Resolution & review', 'Resolve each question against its predefined rule. Preserve unsuccessful forecasts, review errors, and compare performance with a stated benchmark. Leave questions unresolved when their evidence rule is not met.', 'An evaluation component is reported to exist; a validated track record is not established.')
    ]
    steps=''.join(f'<div><span>{i:02}</span><div><h2>{title}</h2><p>{description}</p><small>{status}</small></div></div>' for i,(title,description,status) in enumerate(stages,1))
    return intro('Our approach / Evidence before inference', 'Attention is a starting point.<br><em>Evidence does the work.</em>', 'The Venezuela programme is designed around a traceable chain from source material to a specific client question. Each stage should preserve what is known, what is disputed, and what remains to be established.') + '''<section class="programme-note container"><span class="eyebrow">Method and development status</span><p>This describes the intended workflow and the status reported in the September 2026 working plan. It is not an independent audit of the platform or a claim that the whole chain is operating today.</p></section><section class="container approach-section"><div class="approach-statement"><span class="small-cross">✳</span><h2>Start with the decision.<br>Write a resolvable question.</h2><p>Name one asset, contract, actor, or place. Define a yes-or-no outcome, a deadline, and the evidence that will establish the answer. Agree what happens if that evidence remains unavailable.</p><p>Then ask which events could change the assessment. That is the collection plan: a set of evidence needs tied to a decision.</p><a class="text-link" href="venezuela.html">Explore the worked example </a></div><div class="approach-steps">''' + steps + '''</div></section>
<section class="scenario-section"><div class="container"><div class="section-heading"><div><div class="eyebrow">Reading the event record</div><h2>A label needs<br>an explanation.</h2></div><p>Explore the intended treatment of evidence states. This is an editorial demonstration, not an automated assessment of live sources.</p></div><div class="scenario-controls" role="group" aria-label="Illustrative evidence state"><button data-evidence-state="single" aria-pressed="true">01 / Single source</button><button data-evidence-state="corroborated" aria-pressed="false">02 / Corroborated</button><button data-evidence-state="contradicted" aria-pressed="false">03 / Contradicted</button></div><div class="scenario-content" aria-live="polite"><div><div class="eyebrow">Evidence state</div><h3 id="evidence-title">One evidentiary chain, however many headlines.</h3><p id="evidence-description">Reports trace back to one source or source family. Repetition does not make the underlying account independently confirmed.</p><span class="scenario-badge">METHOD DEMONSTRATION / NO PROBABILITY ASSIGNED</span></div><div class="scenario-tests"><div><span>What to establish</span><p id="evidence-check">Identify the original account, its time and place, and how the source knows.</p></div><div><span>Analyst’s next step</span><p id="evidence-next">Seek an independently obtained account or a different collection method.</p></div><div><span>Freshness is separate</span><p>A record can be corroborated or contradicted and also be stale. Review windows depend on event type; freshness does not settle the disagreement.</p></div></div></div></div></section>
<section class="section container"><div class="section-heading"><div><div class="eyebrow">Three distinctions that matter</div><h2>Keep the meaning<br>of every measure clear.</h2></div></div><div class="standards-grid"><div><h3>Attention ≠ event risk</h3><p>More articles about a topic may signal interest, repeated reporting, or disagreement. It does not by itself show that the event is more likely.</p></div><div><h3>Source type ≠ certainty</h3><p>Field, official, expert, and physical sources have different strengths and limitations. Weighting rules need a documented rationale; none makes a claim automatically true.</p></div><div><h3>A score ≠ proven skill</h3><p>Evaluation needs resolved questions, a consistent scoring policy, and comparison with a reference forecast. No forecasting performance claim is made here.</p></div></div><a class="text-link" href="research/questions-that-can-resolve.html">How to frame and evaluate a question </a></section>''' + cta()
